config/routes.rb
Bitehook::Application.routes.draw do

	resources :attendances
	resources :comments, only: [:create, :destroy]
	resources :events do
		member do
			get :attend
			get :permalink
		end
	end
	resources :payments, only: :index
	resources :users

	# Events
	match 'upcoming' => 'events#upcoming', as: 'upcoming'
	match 'event-list' => 'events#event_list', as: 'event_list'

	# Pages
	root to: 'pages#home'
	match 'about' => 'pages#about', as: 'about'
	match 'test' => 'pages#test', as: 'test'

	# Payments
	match 'confirm_payment/:event_id' => 'payments#confirm_payment', as: 'confirm_payment'

	# Sessions
	match 'auth' => 'sessions#auth', as: 'auth'
	match 'sign-out' => 'sessions#destroy', as: 'sign_out'

	# Users
	match 'user-list' => 'users#user_list', as: 'user_list'

	# 404
	match '*url' => 'pages#not_found', as: 'not_found'
end

app/models/event.rb
class Event < ActiveRecord::Base
	attr_accessible :name,
					:price,
					:date,
					:info,
					:address_1,
					:address_2,
					:city,
					:state,
					:zip_code,
					:image1,
					:image2,
					:image3

	has_many :users, through: :attendances
	has_many :attendances, dependent: :destroy

	has_many :comments, dependent: :destroy

	has_many :payments

	extend FriendlyId
	friendly_id :name, use: :slugged

	validates :name, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :authenticate, except: [:show, :permalink]
	before_filter :admin_user, except: [:attend, :show, :permalink, :upcoming]

	# all users
	def show
		@event = Event.find(params[:id])
		@title = @event.name
		@attending = @event.users.shuffle
		@comments = @event.comments
		store_location
	rescue ActiveRecord::RecordNotFound
		redirect_to upcoming_path
	end

	def permalink
		@event = Event.find(params[:id])
		render layout: false
	end

	# signed in users
	def upcoming
		@title = 'Upcoming Events'
		@events = Event.where('date >= ?', Time.now).order('date ASC')
		render 'index'
	end

	def attend
		event = Event.find(params[:id])
		unless Attendance.find_by_user_id_and_event_id(current_user, event)
			Attendance.create(user_id: current_user.id, event_id: event.id)
		end
		current_user.delay(queue: 'attend', priority: 9).fb_action('attend', event)
		respond_to do |format|
			format.html {
				flash[:success] = 'Thank you for attending, see you there!'
				redirect_to event
			}
			format.js {
				@event = event
			}
		end
	rescue ActiveRecord::RecordNotFound
		redirect_to upcoming_path
	end

	# admin users
	def index
		@title = 'All Events'
		@events = Event.order('date DESC')
	end

	def new
		@title = 'New Event'
		@event = Event.new
	end

	def create
		@event = Event.new(params[:event])
		if @event.save
			flash[:success] = 'Event created'
			redirect_to @event
		else
			@title = 'New Event'
			render 'new'
		end
	end

	def edit
		@event = Event.find(params[:id])
		@title = 'Edit Event'
		render 'new'
	end

	def update
		@event = Event.find(params[:id])
		if @event.update_attributes(params[:event])
			flash[:success] = 'Event updated'
			redirect_to @event
		else
			@title = 'Edit Event'
			render 'new'
		end
	end

	def destroy
		Event.find(params[:id]).destroy
		flash[:success] = 'Event deleted'
		redirect_to events_path
	end

	def event_list
		if Rails.env.production?
			@events = Event.order(:name).where("name ILIKE ? OR info ILIKE ?", "%#{params[:term]}%", "%#{params[:term]}%")
		else
			@events = Event.order(:name).where("name LIKE ? OR price LIKE ? OR date LIKE ? OR info LIKE ? OR address_1 LIKE ? OR address_2 LIKE ? OR city LIKE ? OR state LIKE ? OR zip_code LIKE ?", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%")
		end
		render json: @events.map(&:name)
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attend.html.erb
<% if signed_in? %>
	<% if current_user.attending?(event) %>
		<% if event.date > Time.now %>
			<p id="alreadyAttending">Attending</p>
		<% else %>
			<p id="alreadyAttending">Attended</p>
		<% end %>
	<% else %>
		<%= link_to 'Attend', attend_event_path(event), remote: true %>
	<% end %>
<% else %>
	<%= link_to 'Attend', facebook_url %>
<% end %>

app/views/events/_event.html.erb
<div class="eventShow">
	<div class="eventHeader">
		<div class="eventNav">
			<p id="eventDay"><%= event.date.strftime("%A") %></p>
			<p id="eventDate"><%= event.date.strftime("%b %d, %Y") %></p>
			<ul class="socialShare">
				<li class="eventShareTwitter">
					<%= link_to("http://bitehook.com#{event_path(event)}", id: "tweet_#{event.id}", class: "twitterShare", name: "#{CGI.escape(event.name)}", title: "Twitter") do %>
						<div></div>
					<% end %>
				</li>
				<li class="eventShareFacebook">
					<fb:like href="http://bitehook.com<%= event_path(event) %>" layout="button_count" send="false" show_faces="false">
				</li>
			</ul>
			<div class="clear"></div>
		</div>
		<p id="eventName">
			<span class="eventPrice"><%= number_to_currency(event.price) %></span>
			<%= link_to event.name, event %>
		</p>
	</div>
	<div class="eventInfo">
		<div class="eventSingleImage">
			<%= image_tag event.image1 %>
		</div>
		<div class="eventInfoHeader">
			<p>Location</p>
		</div>
		<div class="address">
			<p><%= event.address_1 %></p>
			<% if event.address_2 %>
				<p><%= event.address_2 %></p>
			<% end %>
			<p><%= event.city %> <%= event.state %>, <%= event.zip_code %></p>
			<p>at <%= event.date.strftime("%l:%M %p") %></p>
		</div>
		<div id="eventSingleAttend_<%= event.id %>" class="eventSingleAttend">
			<%= render partial: 'attend', locals: { event: event } %>
		</div>
		<div class="clear"></div>
	</div>
</div>
<div class="clear"></div>

app/views/events/attend.js.erb
$('.attend').html("<%= escape_javascript(render(partial: 'events/attend', locals: { event: @event })) %>");
$('#eventSingleAttend_' + <%= @event.id %>).html("<%= escape_javascript(render(partial: 'events/attend', locals: { event: @event })) %>");

app/views/events/index.html.erb
<%= content_for :head do %>
	<meta property="og:title" content="Catch a great bite with good people."/>
	<meta property="og:image" content="http://bitehook.com/assets/bitehook.png"/>
	<meta property="og:site_name" content="BiteHook"/>
<% end %>
<div class="events">
	<%= render @events %>
</div>

app/views/events/new.html.erb
<div class="eventForm">
	<p class="formHeader"><%= @title %></p>
	<%= form_for @event do |f| %>
		<div class="form">
			<div class="field">
				<p>Name</p>
				<%= f.text_field :name %>
			</div>
			<div class="field">
				<p>Price</p>
				<%= f.text_field :price %>
			</div>
			<div class="field">
				<p>Date</p>
				<%= f.datetime_select :date, ampm: true, datetime_separator: "", use_short_month: true, order: [:month, :day, :year] %>
			</div>
			<div class="field">
				<p>Address 1</p>
				<%= f.text_field :address_1 %>
			</div>
			<div class="field">
				<p>Address 2</p>
				<%= f.text_field :address_2 %>
			</div>
			<div class="field">
				<p>City</p>
				<%= f.text_field :city %>
			</div>
			<div class="field">
				<p>State</p>
				<%= f.text_field :state %>
			</div>
			<div class="field">
				<p>Zip Code</p>
				<%= f.text_field :zip_code %>
			</div>
			<div class="field">
				<p>Image 1</p>
				<%= f.text_field :image1 %>
			</div>
			<div class="field">
				<p>Image 2</p>
				<%= f.text_field :image2 %>
			</div>
			<div class="field">
				<p>Image 3</p>
				<%= f.text_field :image3 %>
			</div>
			<div class="field">
				<p>Info</p>
				<%= f.text_area :info %>
			</div>
			<div class="action">
				<%= f.submit 'Submit' %>
				<%= link_to 'Cancel', events_path %>
			</div>
		</div>
	<% end %>
</div>

app/views/events/permalink.html.erb
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# bitehook: http://ogp.me/ns/fb/bitehook#">
	<meta property="fb:app_id" content="<%= app_id %>" />
	<meta property="og:type"   content="bitehook:event" />
	<meta property="og:title" content="<%= @event.name %>" />
	<meta property="og:image" content="<%= @event.image1 %>" />
	<meta property="og:description" content="<%= @event.info %>" />
	<meta property="og:url"    content="http://bitehook.com<%= event_path(@event) %>/permalink" />
	<meta property="og:site_name" content="BiteHook" />
</head>
<% if Rails.env.production? %>
<script>
	location.href = "http://bitehook.com<%= event_path(@event) %>"
</script>
<% else %>
<script>
	location.href = "http://localhost:3000<%= event_path(@event) %>"
</script>
<% end %>
<body>
</body>
</html>

app/views/events/show.html.erb
<%= content_for :head do %>
	<meta property="og:title" content="<%= @event.name %>" />
	<meta property="og:image" content="<%= @event.image1 %>" />
	<meta property="og:description" content="<%= @event.info %>" />
	<meta property="og:url"    content="<%= request.url %>" />
	<meta property="og:site_name" content="BiteHook" />
<% end %>
<div class="topButton">
	<%= link_to('#', class: 'toTop') do %>
		<div></div>
	<% end %>
</div>
<div class="eventShow">
	<span class="eventWaypoint1"></span>
	<div class="eventHeader">
		<div class="eventNav">
			<p id="eventDay"><%= @event.date.strftime("%A") %></p>
			<p id="eventDate"><%= @event.date.strftime("%b %d, %Y") %></p>
			<div class="clear"></div>
			<div class="attend">
				<%= render partial: 'attend', locals: { event: @event } %>
			</div>
			<% if signed_in? && current_user.admin? %>
				<div class="attending">
					<% if @attending.empty? %>
						<p>Be the first to attend</p>
					<% else %>
						<p>People Attending</p>
					<% end %>
					<% @attending.each do |user| %>
						<div>
							<%= link_to image_tag(user.image), user, title: user.first_name %>
						</div>
					<% end %>
				</div>
			<% end %>
		</div>
		<span class="eventWaypoint2"></span>
		<p id="eventName">
			<span class="eventPrice"><%= number_to_currency(@event.price) %></span>
			<%= link_to @event.name, @event %>
		</p>
	</div>
	<div class="eventInfo">
		<div class="eventImage">
			<div id="cycle" class="eventImageContainer">
				<% if @event.image1 %>
					<%= image_tag @event.image1 %>
				<% end %>
				<% if @event.image2 %>
					<%= image_tag @event.image2 %>
				<% end %>
				<% if @event.image3 %>
					<%= image_tag @event.image3 %>
				<% end %>
			</div>
		</div>
		<div class="eventInfoHeader">
			<p>Information</p>
		</div>
		<%= to_html(@event.info.html_safe) %>
		<div class="eventInfoHeader">
			<p>Location</p>
		</div>
		<div class="address">
			<p><%= @event.address_1 %></p>
			<% if @event.address_2 %>
				<p><%= @event.address_2 %></p>
			<% end %>
			<p><%= @event.city %> <%= @event.state %>, <%= @event.zip_code %></p>
			<p>at <%= @event.date.strftime("%l:%M %p") %></p>
		</div>
	</div>
	<div class="eventComments">
		<% if signed_in? %>
			<div class="commentForm">
				<%= render 'comments/form' %>
			</div>
		<% end %>
		<div class="commentList">
			<%= render @comments %>
		</div>
	</div>
</div>
<div class="clear"></div>
<% if signed_in? %>
	<% if current_user.admin? %>
	<script>
		$('document').ready(function() {
			$('.headerNav').prepend("<li><a href='<%= event_path(@event) %>/edit' >Edit</a></li>");
		});
	</script>
	<% end %>
<% end %>