config/routes.rb
Bitehook::Application.routes.draw do

	resources :attendances
	resources :comments, only: [:create, :destroy]
	resources :events do
		member do
			get :attend
			get :permalink
		end
	end
	resources :payments, only: :index
	resources :users

	# Events
	match 'upcoming' => 'events#upcoming', as: 'upcoming'
	match 'event-list' => 'events#event_list', as: 'event_list'

	# Pages
	root to: 'pages#home'
	match 'about' => 'pages#about', as: 'about'
	match 'test' => 'pages#test', as: 'test'

	# Payments
	match 'confirm_payment/:event_id' => 'payments#confirm_payment', as: 'confirm_payment'

	# Sessions
	match 'auth' => 'sessions#auth', as: 'auth'
	match 'sign-out' => 'sessions#destroy', as: 'sign_out'

	# Users
	match 'user-list' => 'users#user_list', as: 'user_list'

	# 404
	match '*url' => 'pages#not_found', as: 'not_found'
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	attr_accessible :user_id, :event_id
	
	belongs_to :user
	belongs_to :event

	validates :user_id, presence: true
	validates :event_id, presence: true
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
	before_filter :authenticate
	before_filter :admin_user

	def index
		@title = 'All Attendances'
		@attendances = Attendance.order('created_at DESC')
	end

	def new
		@title = 'New Attendance'
		@attendance = Attendance.new
	end

	def create
		user = User.find_by_name("#{params[:user_name]}")
		event = Event.find_by_name("#{params[:event_name]}")
		if user && event && Attendance.find_by_user_id_and_event_id(user.id, event.id).nil?
			Attendance.create!(user_id: user.id, event_id: event.id)
			flash[:success] = "#{user.name} is now attending #{event.name}"
		else
			flash[:error] = "Attendance was not created"
		end
		redirect_to attendances_path
	end

	def edit
		@title = 'Edit Attendance'
		@attendance = Attendance.find(params[:id])
		@user = @attendance.user
		@event = @attendance.event
	end

	def update
		user = User.find_by_name("#{params[:user_name]}")
		event = Event.find_by_name("#{params[:event_name]}")
		attendance = Attendance.find(params[:id])
		if user && event && Attendance.find_by_user_id_and_event_id(user.id, event.id).nil? && attendance.update_attributes(user_id: user.id, event_id: event.id)
			flash[:success] = "Attendance updated"
		else
			flash[:error] = "Attendance failed to update, could not find user or event with that name"
		end
		redirect_to attendances_path
	end

	def destroy
		Attendance.find(params[:id]).destroy
		flash[:success] = 'Attendance deleted'
		redirect_to attendances_path
	end
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/views/attendances/edit.html.erb
<div class="eventForm attendanceForm">
	<p class="formHeader"><%= @title %></p>
	<%= form_for @attendance do |f| %>
		<div class="form">
			<div class="field">
				<p>User</p>
				<%= text_field_tag :user_name, "#{@user.name}", data: { autocomplete_source: user_list_path } %>
			</div>
			<div class="field">
				<p>Event</p>
				<%= text_field_tag :event_name, "#{@event.name}", data: { autocomplete_source: event_list_path } %>
			</div>
			<div class="action">
				<%= f.submit 'Submit' %>
				<%= link_to 'Cancel', attendances_path %>
			</div>
		</div>
	<% end %>
</div>

app/views/attendances/index.html.erb
<div class="payments">
	<ol>
		<% @attendances.each do |attendance| %>
			<li>
				<div class="payment">
					<p><%= attendance.created_at.strftime("%b %d, %y at %I:%M %P") %></p>
					<p>
						<%= link_to attendance.user.name, attendance.user %> 
						is attending 
						<%= link_to attendance.event.name, attendance.event %>
					</p>
					<p><%= link_to 'Edit', edit_attendance_path(attendance) %> | <%= link_to 'Delete', attendance, method: :delete, confirm: 'Are you sure you want to delete?' %></p>
				</div>
			</li>
		<% end %>
	</ol>
</div>

app/views/attendances/new.html.erb
<div class="eventForm attendanceForm">
	<p class="formHeader"><%= @title %></p>
	<%= form_for @attendance do |f| %>
		<div class="form">
			<div class="field">
				<p>User</p>
				<%= text_field_tag :user_name, '', data: { autocomplete_source: user_list_path } %>
			</div>
			<div class="field">
				<p>Event</p>
				<%= text_field_tag :event_name, '', data: { autocomplete_source: event_list_path } %>
			</div>
			<div class="action">
				<%= f.submit 'Submit' %>
				<%= link_to 'Cancel', attendances_path %>
			</div>
		</div>
	<% end %>
</div>