config/routes.rb
Bitehook::Application.routes.draw do

	resources :attendances
	resources :comments, only: [:create, :destroy]
	resources :events do
		member do
			get :attend
			get :permalink
		end
	end
	resources :payments, only: :index
	resources :users

	# Events
	match 'upcoming' => 'events#upcoming', as: 'upcoming'
	match 'event-list' => 'events#event_list', as: 'event_list'

	# Pages
	root to: 'pages#home'
	match 'about' => 'pages#about', as: 'about'
	match 'test' => 'pages#test', as: 'test'

	# Payments
	match 'confirm_payment/:event_id' => 'payments#confirm_payment', as: 'confirm_payment'

	# Sessions
	match 'auth' => 'sessions#auth', as: 'auth'
	match 'sign-out' => 'sessions#destroy', as: 'sign_out'

	# Users
	match 'user-list' => 'users#user_list', as: 'user_list'

	# 404
	match '*url' => 'pages#not_found', as: 'not_found'
end

app/views/layouts/_footer.html.erb
<div class="copyright">
	<p>BiteHook &copy; 2013 All Rights Reserved.</p>
</div>

app/views/layouts/_header.html.erb
<div class="inHeader">
	<%= link_to root_path do %>
		<%= image_tag "/assets/logo.png", class: "logo" %>
	<% end %>
	<% if signed_in? %>
		<div class="rightNav">
			<div class="accountMenu">
				<ul>
					<% if current_user.admin? %>
						<li><%= link_to 'Events', events_path %></li>
						<li><%= link_to 'Users', users_path %></li>
						<li><%= link_to 'Payments', payments_path %></li>
						<li><%= link_to 'Attendances', attendances_path %></li>
					<% end %>
					<li><%= link_to 'My Bites', current_user %></li>
					<li><%= link_to 'Settings', edit_user_path(current_user) %></li>
					<li><%= link_to 'Sign Out', sign_out_path %></li>
				</ul>
			</div>
		</div>
	<% end %>
	<div class="rightNav">
		<ul class="headerNav">
			<% if signed_in? && current_user.admin? %>
				<li><%= link_to 'New Event', new_event_path %></li>
			<% end %>
			<li>
				<% if signed_in? %>
					<%= link_to 'Upcoming Events', upcoming_path %>
				<% else %>
					<% if request.fullpath == '/' %>
						<%= link_to 'How It Works', '#works' %>
					<% else %>
						<%= link_to 'How It Works', '/#works' %>
					<% end %>
				<% end %>
			</li>
			<li>
				<% if signed_in? %>
					<%= link_to "#{current_user.first_name}", current_user, class: 'account' %>
				<% else %>
					<%= link_to 'Sign In', facebook_url %>
				<% end %>
			</li>
		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# bitehook: http://ogp.me/ns/fb/bitehook#">
	<title><%= title %></title>
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= favicon_link_tag 'favicon.ico' %>
	<meta charset="UTF-8">
	<%= yield :head %>
	<script type="text/javascript">
		// Facebook
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));

		// Twitter
		!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
	</script>
</head>
<body>
	<div class="wrapper">
		<div class="header">
			<%= render 'layouts/header' %>
		</div>
		<div class="content">
			<% flash.each do |key, value| %>
				<div class="flash <%= key %>">
					<%= link_to image_tag('/assets/close.png'), '#', class: 'closeFlash', title: "Close" %>
					<p><%= value %></p>
				</div>
			<% end %>
			<%= yield %>
		</div>
	</div>
	<div class="footer">
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>